import logging
from typing import Any, Optional

import requests

from . import config


class Client:
    def __init__(self, cfg: config.Config):
        self.uri = cfg.influxdb_uri
        self.token = cfg.influxdb_token
        self.headers = {
            "Authorization": f"token {self.token}",
            "Content-Type": "application/json",
        }

    def get(self, path: str) -> Any:
        res: requests.Response = requests.get(self.uri + path, headers=self.headers)
        if res.status_code == 401:
            logging.error("user is unauthorized for getting!")
            return None
        res.raise_for_status
        return res.json()

    def post(self, path: str, payload: Optional[dict[Any, Any]] = None) -> Any:
        res: requests.Response = requests.post(
            self.uri + path, headers=self.headers, json=payload
        )
        if res.status_code == 401:
            logging.error("user is unauthorized for creating!")
            return None
        res.raise_for_status
        return res.json()

    def delete(self, path: str):
        res: requests.Response = requests.delete(
            self.uri + path,
            headers=self.headers,
        )
        if res.status_code == 401:
            logging.error("user is unauthorized for deleting!")
            return None
        res.raise_for_status
        return res.json()


class Org:
    def __init__(self, id: Optional[str], name: str, client: Client):
        self.id = id
        self.name = name
        self.client = client

    def create(self):
        logging.info(f"creating org {self.name}")
        res = self.client.post("/api/v2/orgs", payload={"name": self.name})
        self.id = res.get("id")
        logging.info("successfully created org")


class Bucket:
    def __init__(self, id: Optional[str], name: str, org: Org, client: Client):
        self.id = id
        self.name = name
        self.org = org
        self.client = client

    def create(self):
        logging.info(f"creating bucket {self.name} in {self.org.name}")
        payload = {
            "name": self.name,
            "orgId": self.org.id,
        }
        res = self.client.post("/api/v2/orgs", payload=payload)
        self.id = res.get("id")
        logging.info("successfully created bucket")


class Token:
    def __init__(
        self,
        name: str,
        org: Org,
        client: Client,
        permissions: str,
        id: Optional[str] = None,
        bucket: Optional[Bucket] = None,
    ):
        self.name = name
        self.id = id
        self.org = org
        self.client = client
        self.bucket = bucket
        self.permissions = permissions

    def create(self):
        logging.info(
            f"creating token {self.name} in {self.org.name} with {self.permissions}"
        )
        resource = {
            "orgId": self.org.id,
        }
        if self.bucket is not None:
            logging.info(
                f"scoping permissions of {self.name} to bucket {self.bucket.name}"
            )
            resource["type"] = "buckets"
            resource["name"] = self.bucket.name
        payload = {
            "status": "active",
            "description": f"autogenerated token for {self.name} secret",
            "orgId": self.org.id,
            "permissions": [
                {
                    "action": self.permissions,
                    "resource": resource,
                },
            ],
        }
        raw_token = self.client.post("/api/v2/authorizations", payload)
        self.id = raw_token.get("id")
        self.token = raw_token.get("token")
        logging.info("successfully created token")

    def delete(self):
        logging.info(f"deleting token {self.name} in {self.org.name}")
        self.client.delete("/api/v2/authorizations")
        logging.info("successfully deleted token")


def get_orgs(client: Client) -> list[Org]:
    raw_orgs = client.get("/api/v2/orgs")
    orgs: list[Org] = []
    for org_json in raw_orgs:
        orgs.append(Org(org_json["id"], org_json["name"], client))
    return orgs


def get_buckets(client: Client, org: Org) -> list[Bucket]:
    raw_buckets = client.get(f"/api/v2/buckets?orgID={org.id}")
    buckets: list[Bucket] = []
    for bucket_json in raw_buckets:
        buckets.append(Bucket(bucket_json["id"], bucket_json["name"], org, client))
    return buckets


def get_tokens(
    client: Client,
) -> list[Token]:
    raw_tokens = client.get("/api/v2/authorization")
    tokens: list[Token] = []
    for token_json in raw_tokens:
        org = Org(token_json["orgId"], token_json["org"], client)
        permissions = token_json["permissions"]
        bucket = None
        if permissions[0].get("name"):
            bucket = Bucket(permissions[0]["id"], permissions[0]["name"], org, client)
        tokens.append(
            Token(
                token_json["name"],
                org,
                client,
                permissions["action"],
                token_json["id"],
                bucket,
            )
        )
    return tokens
