---
name: Release Charts
on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"


      - name: get version
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
          run: |
            python ./scripts/get_version.py


      - name: install helm
        uses: azure/setup-helm@v3


      - name: package helm chart
        run: |
          helm package ./helm/ \
            --destination ./charts \
            --app-version=${{CURRENT_VERSION}}


      - name: run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
